parameters: 
- name: stageName
  default: ''
- name: environment
  default: ''
- name: azureSubscription
  default: ''
- name: resourceGroupName
  default: ''
- name: webAppName
  default: ''
- name: region
  default: ''
- name: packageName
  default: ''  

stages:
  - stage: ${{ parameters.stageName }}
    displayName: ${{ parameters.stageName }}

    jobs:
    - deployment: Deploy
      displayName: Deploy
      environment: ${{ parameters.environment }}
      pool:
        vmImage: 'ubuntu-latest'
  
      strategy:
        runOnce:
          deploy:
  
            steps:
            - task: AzureCLI@2
              displayName: '1. Deploy Azure Resources'
              inputs:
                azureSubscription: ${{ parameters.azureSubscription }}
                scriptType: bash
                scriptLocation: inlineScript
                inlineScript: |
                  az group create --name ${{ parameters.resourceGroupName }} --location ${{ parameters.region }}
                  az deployment group create --resource-group ${{ parameters.resourceGroupName }} --template-file $(Pipeline.Workspace)/build/Infrastructure/main.bicep --parameters webAppName=${{ parameters.webAppName }} functionAppStorageAccountName=${{ parameters.storageAccountName }} location=${{ parameters.region }}  > outputs.json

            - task: AzureRmWebAppDeployment@4
              displayName: '2. Deploy Application Code'
              inputs:
                ConnectionType: 'AzureRM'
                azureSubscription: ${{ parameters.azureSubscription }}
                appType: webApp
                WebAppName: ${{ parameters.webAppName }}
                package: '$(Pipeline.Workspace)/build/App/${{ parameters.packageName }}'
                AppSettings: ''